CREATE TABLE `favorites` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`food_id` integer NOT NULL,
	`created_at` text NOT NULL,
	FOREIGN KEY (`food_id`) REFERENCES `foods`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `foods` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`is_custom` integer NOT NULL,
	`is_verified` integer NOT NULL,
	`name` text NOT NULL,
	`producer` text,
	`serving_quantity` integer NOT NULL,
	`amount` integer NOT NULL,
	`base_unit` text NOT NULL,
	`energy` real NOT NULL,
	`protein` real NOT NULL,
	`carb` real NOT NULL,
	`dietary_fiber` real,
	`sugar` real NOT NULL,
	`fat` real NOT NULL,
	`saturated_fat` real NOT NULL,
	`mono_unsaturated_fat` real,
	`poly_unsaturated_fat` real,
	`trans_fat` real,
	`alcohol` real,
	`cholesterol` real,
	`sodium` real,
	`salt` real NOT NULL,
	`water` real,
	`vitamin_a` real,
	`vitamin_b1` real,
	`vitamin_b2` real,
	`vitamin_b3` real,
	`vitamin_b5` real,
	`vitamin_b6` real,
	`vitamin_b7` real,
	`vitamin_b11` real,
	`vitamin_b12` real,
	`vitamin_c` real,
	`vitamin_d` real,
	`vitamin_e` real,
	`vitamin_k` real,
	`arsenic` real,
	`biotin` real,
	`boron` real,
	`chloride` real,
	`choline` real,
	`chromium` real,
	`iron` real,
	`fluorine` real,
	`fluoride` real,
	`iodine` real,
	`potassium` real,
	`calcium` real,
	`cobalt` real,
	`copper` real,
	`magnesium` real,
	`manganese` real,
	`molybdenum` real,
	`phosphorus` real,
	`rubidium` real,
	`sulfur` real,
	`selenium` real,
	`silicon` real,
	`vanadium` real,
	`zinc` real,
	`tin` real
);
--> statement-breakpoint
CREATE TABLE `meals` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`food_id` integer NOT NULL,
	`meal_type` text NOT NULL,
	`date` text NOT NULL,
	FOREIGN KEY (`food_id`) REFERENCES `foods`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `recents` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`food_id` integer NOT NULL,
	`updated_at` text NOT NULL,
	`count` integer NOT NULL,
	`serving_amount` integer NOT NULL,
	FOREIGN KEY (`food_id`) REFERENCES `foods`(`id`) ON UPDATE no action ON DELETE no action
);
