export enum ServingType {
  Serving = "Serving",
  Package = "Package",
  Slice = "Slice",
  Each = "Each",
  Piece = "Piece",
  Bar = "Bar",
  Bottle = "Bottle",
  Can = "Can",
  Cup = "Cup",
  Glass = "Glass",
  Bowl = "Bowl",
  Bag = "Bag",
  Portion = "Portion",
  Tablespoon = "Tablespoon",
  Teaspoon = "Teaspoon",
  Tablet = "Tablet",
  Plate = "Plate",
  Whole = "Whole",
}
